<a href="https://colab.research.google.com/github/Jualeon/AP0053-20243/blob/main/Udmy17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
insta = pd.read_csv('/content/drive/MyDrive/Instagram.csv')
insta.head()

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
0,Corilla,Leuchars,Female,2/11/2011,2020-05-14 3:51,24536,462,False,Brazil
1,Forster,Gush,Male,4/2/2015,2020-07-11 7:41,8479,2581,True,United States
2,Everard,Jowers,Male,11/14/2018,2020-05-31 17:36,9356,6874,False,United Kingdom
3,Bob,Threader,Male,6/13/2019,2020-07-04 16:19,33319,3617,False,Australia
4,Deeann,Standell,Female,4/26/2011,2020-10-03 6:16,2908,98,False,NaN

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
insta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016 entries, 0 to 1015
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   first name  1016 non-null   object
 1   last name   1016 non-null   object
 2   gender      979 non-null    object
 3   reg date    1016 non-null   object
 4   last login  1016 non-null   object
 5   followers   1016 non-null   int64
 6   posts       1016 non-null   int64
 7   Influencer  994 non-null    object
 8   Country     1004 non-null   object
dtypes: int64(2), object(7)
memory usage: 71.6+ KB

In [4]:
insta = pd.read_csv("/content/drive/MyDrive/Instagram.csv")
insta

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
0,Corilla,Leuchars,Female,2/11/2011,2020-05-14 3:51,24536,462,False,Brazil
1,Forster,Gush,Male,4/2/2015,2020-07-11 7:41,8479,2581,True,United States
2,Everard,Jowers,Male,11/14/2018,2020-05-31 17:36,9356,6874,False,United Kingdom
3,Bob,Threader,Male,6/13/2019,2020-07-04 16:19,33319,3617,False,Australia
4,Deeann,Standell,Female,4/26/2011,2020-10-03 6:16,2908,98,False,NaN
...,...,...,...,...,...,...,...,...,...
1011,Lars,Crisp,Male,12/30/2012,2020-12-11 8:20,787,388,False,Canada
1012,Yvon,Goodbur,Male,9/29/2011,2020-09-20 17:36,18906,3851,False,Canada
1013,Pattie,Goody,Female,11/9/2015,2020-07-07 14:41,32425,6376,True,United States
1014,Sol,Andrysek,Male,2/19/2011,2020-10-18 16:06,475,7409,True,Brazil
1015,Regine,Bernholt,Female,11/15/2013,2020-05-23 14:23,19535,6927,True,Canada

In [5]:
insta["reg date"] = pd.to_datetime(insta["reg date"])
insta

,first name,last name,gender,reg date,last login,followers,posts,Influencer,Country
0,Corilla,Leuchars,Female,2011-02-11,2020-05-14 3:51,24536,462,False,Brazil
1,Forster,Gush,Male,2015-04-02,2020-07-11 7:41,8479,2581,True,United States
2,Everard,Jowers,Male,2018-11-14,2020-05-31 17:36,9356,6874,False,United Kingdom
3,Bob,Threader,Male,2019-06-13,2020-07-04 16:19,33319,3617,False,Australia
4,Deeann,Standell,Female,2011-04-26,2020-10-03 6:16,2908,98,False,NaN
...,...,...,...,...,...,...,...,...,...
1011,Lars,Crisp,Male,2012-12-30,2020-12-11 8:20,787,388,False,Canada
1012,Yvon,Goodbur,Male,2011-09-29,2020-09-20 17:36,18906,3851,False,Canada
1013,Pattie,Goody,Female,2015-11-09,2020-07-07 14:41,32425,6376,True,United States
1014,Sol,Andrysek,Male,2011-02-19,2020-10-18 16:06,475,7409,True,Brazil
1015,Regine,Bernholt,Female,2013-11-15,2020-05-23 14:23,19535,6927,True,Canada

In [6]:
insta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016 entries, 0 to 1015
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   first name  1016 non-null   object
 1   last name   1016 non-null   object
 2   gender      979 non-null    object
 3   reg date    1016 non-null   datetime64[ns]
 4   last login  1016 non-null   object
 5   followers   1016 non-null   int64
 6   posts       1016 non-null   int64
 7   Influencer  994 non-null    object
 8   Country     1004 non-null   object
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 71.6+ KB

In [7]:
insta["last login"] = pd.to_datetime(insta["last login"])
#insta.drop("last login", axis = 1, inplace = True)
insta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016 entries, 0 to 1015
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   first name  1016 non-null   object
 1   last name   1016 non-null   object
 2   gender      979 non-null    object
 3   reg date    1016 non-null   datetime64[ns]
 4   last login  1016 non-null   datetime64[ns]
 5   followers   1016 non-null   int64
 6   posts       1016 non-null   int64
 7   Influencer  994 non-null    object
 8   Country     1004 non-null   object
dtypes: datetime64[ns](2), int64(2), object(5)
memory usage: 71.6+ KB

In [8]:
insta["gender"].nunique()

2

In [9]:
insta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016 entries, 0 to 1015
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   first name  1016 non-null   object
 1   last name   1016 non-null   object
 2   gender      979 non-null    object
 3   reg date    1016 non-null   datetime64[ns]
 4   last login  1016 non-null   datetime64[ns]
 5   followers   1016 non-null   int64
 6   posts       1016 non-null   int64
 7   Influencer  994 non-null    object
 8   Country     1004 non-null   object
dtypes: datetime64[ns](2), int64(2), object(5)
memory usage: 71.6+ KB

In [10]:
insta["gender"].astype("category")

0       Female
1         Male
2         Male
3         Male
4       Female
         ...
1011      Male
1012      Male
1013    Female
1014      Male
1015    Female
Name: gender, Length: 1016, dtype: category
Categories (2, object): ['Female', 'Male']

In [11]:
insta["gender"] = insta["gender"].astype("category")
insta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016 entries, 0 to 1015
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   first name  1016 non-null   object
 1   last name   1016 non-null   object
 2   gender      979 non-null    category
 3   reg date    1016 non-null   datetime64[ns]
 4   last login  1016 non-null   datetime64[ns]
 5   followers   1016 non-null   int64
 6   posts       1016 non-null   int64
 7   Influencer  994 non-null    object
 8   Country     1004 non-null   object
dtypes: category(1), datetime64[ns](2), int64(2), object(4)
memory usage: 64.7+ KB

In [12]:
insta["Country"]

0               Brazil
1        United States
2       United Kingdom
3            Australia
4                  NaN
             ...
1011            Canada
1012            Canada
1013     United States
1014            Brazil
1015            Canada
Name: Country, Length: 1016, dtype: object