<a href="https://colab.research.google.com/github/Jualeon/AP0053-20243/blob/main/Udmy2_dataframes_from_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
numbers = [1, 2, 3, 4, 5, 6]

In [5]:
pd.DataFrame(numbers)

   0
0  1
1  2
2  3
3  4
4  5
5  6

In [6]:
data = [["Jhon", 23], ["Mary", 18], ["Jhon", 31]]

In [10]:
pd.DataFrame(data)

      0   1
0  Jhon  23
1  Mary  18
2  Jhon  31

In [12]:
pd.DataFrame(data, columns= ["Name", "Age"])

   Name  Age
0  Jhon   23
1  Mary   18
2  Jhon   31

In [13]:
pd.DataFrame(data, columns= ["Name", "Age"], index = ["id1", "id2", "id3"])

     Name  Age
id1  Jhon   23
id2  Mary   18
id3  Jhon   31